#ifndef TAIYIN_APPARENT_POSITION_H
#define TAIYIN_APPARENT_POSITION_H

#include "internal/ephemeris_block.h"

#include <cstdint>

namespace taiyin {

const uint32_t TAIYIN_APPARENT_LIGHT_TIME = 1u << 0;
const uint32_t TAIYIN_APPARENT_USE_MATRIX = 1u << 1;
const uint32_t TAIYIN_APPARENT_SPHERICAL = 1u << 2;
const uint32_t TAIYIN_APPARENT_ABERRATION = 1u << 3;
const uint32_t TAIYIN_APPARENT_DEFLECTION = 1u << 4;
const uint32_t TAIYIN_APPARENT_VELOCITY = 1u << 5;
const uint32_t TAIYIN_APPARENT_ACCELERATION = 1u << 6;
const uint32_t TAIYIN_APPARENT_SHAPIRO_DELAY = 1u << 7;
const uint32_t TAIYIN_APPARENT_TOPOCENTRIC = 1u << 8;

const int TAIYIN_APPARENT_FRAME_ICRF = 0;
const int TAIYIN_APPARENT_FRAME_TRUE_EQUATOR_OF_DATE = 1;
const int TAIYIN_APPARENT_FRAME_TRUE_ECLIPTIC_OF_DATE = 2;

bool taiyin_calc_apparent_matrices_flat(
    double jd_tt,
    uint32_t flags,
    int output_frame_id,
    int precession_model_id,
    int nutation_model_id,
    int obliquity_model_id,
    double matrix_derivative_step_days,
    double out_precession_matrix[9],
    double out_nutation_matrix[9],
    double out_output_matrix[9],
    double out_output_matrix_dot[9],
    double out_output_matrix_ddot[9],
    double* out_mean_obliquity_rad,
    double* out_true_obliquity_rad,
    double* out_nutation_dpsi_rad,
    double* out_nutation_deps_rad
) noexcept;

bool taiyin_calc_apparent_with_matrix_flat(
    double jd_tdb,
    int target_id,
    const internal::CompiledEphemerisBlock* target_block,
    int observer_id,
    const internal::CompiledEphemerisBlock* observer_block,
    const double observer_offset_pos_au[3],
    const double observer_offset_vel_au_per_day[3],
    const double observer_offset_acc_au_per_day2[3],
    int deflector_count,
    int solar_deflector_index,
    const int* deflector_ids,
    const internal::CompiledEphemerisBlock* const* deflector_blocks,
    const double* deflector_schwarzschild_radius_au,
    const double* deflector_limit,
    uint32_t flags,
    int light_time_method_id,
    int shapiro_delay_model_id,
    int aberration_model_id,
    int deflection_model_id,
    int max_light_time_iterations,
    double light_time_tolerance_days,
    const double output_matrix[9],
    const double output_matrix_dot[9],
    const double output_matrix_ddot[9],
    double out_geometric_pos_au[3],
    double out_geometric_vel_au_per_day[3],
    double out_geometric_acc_au_per_day2[3],
    double out_astrometric_pos_au[3],
    double out_astrometric_vel_au_per_day[3],
    double out_astrometric_acc_au_per_day2[3],
    double out_deflected_pos_au[3],
    double out_deflected_vel_au_per_day[3],
    double out_deflected_acc_au_per_day2[3],
    double out_aberrated_pos_au[3],
    double out_aberrated_vel_au_per_day[3],
    double out_aberrated_acc_au_per_day2[3],
    double out_apparent_pos_au[3],
    double out_apparent_vel_au_per_day[3],
    double out_apparent_acc_au_per_day2[3],
    double* out_lon_rad,
    double* out_lat_rad,
    double* out_distance_au,
    double* out_lon_rate_rad_per_day,
    double* out_lat_rate_rad_per_day,
    double* out_distance_rate_au_per_day,
    double* out_lon_acc_rad_per_day2,
    double* out_lat_acc_rad_per_day2,
    double* out_distance_acc_au_per_day2,
    double* out_light_time_days,
    double* out_light_time_rate,
    double* out_light_time_acceleration,
    int* out_light_time_iterations
) noexcept;

bool taiyin_calc_apparent_batch_with_matrix_flat(
    double jd_tdb,
    int target_count,
    const int* target_ids,
    const internal::CompiledEphemerisBlock* const* target_blocks,
    int observer_id,
    const internal::CompiledEphemerisBlock* observer_block,
    const double observer_offset_pos_au[3],
    const double observer_offset_vel_au_per_day[3],
    const double observer_offset_acc_au_per_day2[3],
    int deflector_count,
    int solar_deflector_index,
    const int* deflector_ids,
    const internal::CompiledEphemerisBlock* const* deflector_blocks,
    const double* deflector_schwarzschild_radius_au,
    const double* deflector_limit,
    uint32_t flags,
    int light_time_method_id,
    int shapiro_delay_model_id,
    int aberration_model_id,
    int deflection_model_id,
    int max_light_time_iterations,
    double light_time_tolerance_days,
    const double output_matrix[9],
    const double output_matrix_dot[9],
    const double output_matrix_ddot[9],
    double* out_apparent_pos_au,
    double* out_apparent_vel_au_per_day,
    double* out_apparent_acc_au_per_day2,
    double* out_lon_rad,
    double* out_lat_rad,
    double* out_distance_au,
    double* out_lon_rate_rad_per_day,
    double* out_lat_rate_rad_per_day,
    double* out_distance_rate_au_per_day,
    double* out_lon_acc_rad_per_day2,
    double* out_lat_acc_rad_per_day2,
    double* out_distance_acc_au_per_day2,
    double* out_light_time_days,
    double* out_light_time_rate,
    double* out_light_time_acceleration,
    int* out_light_time_iterations
) noexcept;

bool taiyin_calc_apparent_batch_flat(
    double jd_tdb,
    double jd_tt,
    int target_count,
    const int* target_ids,
    const internal::CompiledEphemerisBlock* const* target_blocks,
    int observer_id,
    const internal::CompiledEphemerisBlock* observer_block,
    const double observer_offset_pos_au[3],
    const double observer_offset_vel_au_per_day[3],
    const double observer_offset_acc_au_per_day2[3],
    int deflector_count,
    int solar_deflector_index,
    const int* deflector_ids,
    const internal::CompiledEphemerisBlock* const* deflector_blocks,
    const double* deflector_schwarzschild_radius_au,
    const double* deflector_limit,
    uint32_t flags,
    int output_frame_id,
    int light_time_method_id,
    int shapiro_delay_model_id,
    int aberration_model_id,
    int deflection_model_id,
    int precession_model_id,
    int nutation_model_id,
    int obliquity_model_id,
    int max_light_time_iterations,
    double light_time_tolerance_days,
    double matrix_derivative_step_days,
    double* out_apparent_pos_au,
    double* out_apparent_vel_au_per_day,
    double* out_apparent_acc_au_per_day2,
    double* out_lon_rad,
    double* out_lat_rad,
    double* out_distance_au,
    double* out_lon_rate_rad_per_day,
    double* out_lat_rate_rad_per_day,
    double* out_distance_rate_au_per_day,
    double* out_lon_acc_rad_per_day2,
    double* out_lat_acc_rad_per_day2,
    double* out_distance_acc_au_per_day2,
    double* out_light_time_days,
    double* out_light_time_rate,
    double* out_light_time_acceleration,
    int* out_light_time_iterations
) noexcept;

bool taiyin_calc_apparent_flat(
    double jd_tdb,
    double jd_tt,
    int target_id,
    const internal::CompiledEphemerisBlock* target_block,
    int observer_id,
    const internal::CompiledEphemerisBlock* observer_block,
    const double observer_offset_pos_au[3],
    const double observer_offset_vel_au_per_day[3],
    const double observer_offset_acc_au_per_day2[3],
    int deflector_count,
    int solar_deflector_index,
    const int* deflector_ids,
    const internal::CompiledEphemerisBlock* const* deflector_blocks,
    const double* deflector_schwarzschild_radius_au,
    const double* deflector_limit,
    uint32_t flags,
    int output_frame_id,
    int light_time_method_id,
    int shapiro_delay_model_id,
    int aberration_model_id,
    int deflection_model_id,
    int precession_model_id,
    int nutation_model_id,
    int obliquity_model_id,
    int max_light_time_iterations,
    double light_time_tolerance_days,
    double matrix_derivative_step_days,
    double out_geometric_pos_au[3],
    double out_geometric_vel_au_per_day[3],
    double out_geometric_acc_au_per_day2[3],
    double out_astrometric_pos_au[3],
    double out_astrometric_vel_au_per_day[3],
    double out_astrometric_acc_au_per_day2[3],
    double out_deflected_pos_au[3],
    double out_deflected_vel_au_per_day[3],
    double out_deflected_acc_au_per_day2[3],
    double out_aberrated_pos_au[3],
    double out_aberrated_vel_au_per_day[3],
    double out_aberrated_acc_au_per_day2[3],
    double out_apparent_pos_au[3],
    double out_apparent_vel_au_per_day[3],
    double out_apparent_acc_au_per_day2[3],
    double* out_lon_rad,
    double* out_lat_rad,
    double* out_distance_au,
    double* out_lon_rate_rad_per_day,
    double* out_lat_rate_rad_per_day,
    double* out_distance_rate_au_per_day,
    double* out_lon_acc_rad_per_day2,
    double* out_lat_acc_rad_per_day2,
    double* out_distance_acc_au_per_day2,
    double* out_light_time_days,
    double* out_light_time_rate,
    double* out_light_time_acceleration,
    int* out_light_time_iterations
) noexcept;

}  // namespace taiyin

#endif  // TAIYIN_APPARENT_POSITION_H
