#ifndef TAIYIN_PHYSICAL_CONSTANTS_H
#define TAIYIN_PHYSICAL_CONSTANTS_H

#include "taiyin/angle.h"
#include "taiyin/time.h"

namespace taiyin {

const double TAIYIN_AU_KM = 149597870.7;
const double TAIYIN_AU_M = 1000.0 * TAIYIN_AU_KM;
const double TAIYIN_AU_PER_PARALLAX_MAS = 1000.0 * TAIYIN_RAD_TO_ARCSEC;
const double TAIYIN_KM_PER_S_TO_AU_PER_DAY = SECONDS_PER_DAY / TAIYIN_AU_KM;
const double TAIYIN_MAS_PER_YEAR_TO_RAD_PER_DAY = TAIYIN_MAS_TO_RAD / DAYS_PER_JULIAN_YEAR;
const double TAIYIN_EARTH_ROTATION_RATE_RAD_PER_DAY = TAIYIN_TWO_PI * 1.00273781191135448;
const double TAIYIN_GAUSSIAN_GRAVITATIONAL_CONSTANT = 0.01720209895;
const double TAIYIN_SOLAR_MU_AU3_DAY2 = TAIYIN_GAUSSIAN_GRAVITATIONAL_CONSTANT * TAIYIN_GAUSSIAN_GRAVITATIONAL_CONSTANT;
const double TAIYIN_J2000_MEAN_OBLIQUITY_RAD = 84381.406 * TAIYIN_ARCSEC_TO_RAD;
const double TAIYIN_MOSHIER_J2000_OBLIQUITY_RAD = 23.4392911 * TAIYIN_DEG_TO_RAD;

}  // namespace taiyin

#endif  // TAIYIN_PHYSICAL_CONSTANTS_H
