#ifndef TAIYIN_STATUS_H
#define TAIYIN_STATUS_H

#include <stdint.h>

namespace taiyin {

typedef int32_t TaiyinStatus;

enum TaiyinStatusCode {
    TAIYIN_STATUS_OK = 0,

    TAIYIN_ERROR_INVALID_ARGUMENT = -1,
    TAIYIN_ERROR_OUT_OF_MEMORY = -2,
    TAIYIN_ERROR_INTERNAL = -3,
    TAIYIN_ERROR_UNSUPPORTED = -4,

    TAIYIN_EPHEMERIS_ERROR_NO_ROUTE = -1001,
    TAIYIN_EPHEMERIS_ERROR_COVERAGE_GAP = -1002,
    TAIYIN_EPHEMERIS_ERROR_LOAD_FAILED = -1003,
    TAIYIN_EPHEMERIS_ERROR_EVAL_FAILED = -1004,

    TAIYIN_EPHEMERIS_ERROR_COMPOSITE_MISSING_COMPONENT = -1010,
    TAIYIN_EPHEMERIS_ERROR_COMPOSITE_COVERAGE_GAP = -1011,
    TAIYIN_EPHEMERIS_ERROR_COMPOSITE_METHOD_MISMATCH = -1012,

    TAIYIN_FILE_ERROR_NOT_FOUND = -2001,
    TAIYIN_FILE_ERROR_BAD_FORMAT = -2002,
    TAIYIN_FILE_ERROR_UNSUPPORTED_FORMAT = -2003,
    TAIYIN_FILE_ERROR_DISCOVERY_FAILED = -2004,

    TAIYIN_RUNTIME_ERROR_NOT_INITIALIZED = -6001,
    TAIYIN_RUNTIME_ERROR_CACHE_INSERT_FAILED = -6002,
    TAIYIN_RUNTIME_ERROR_REGISTRY_FAILED = -6003,
};

enum TaiyinStatusCategory {
    TAIYIN_STATUS_CATEGORY_OK = 0,
    TAIYIN_STATUS_CATEGORY_GENERIC = 1,
    TAIYIN_STATUS_CATEGORY_EPHEMERIS = 10,
    TAIYIN_STATUS_CATEGORY_FILE = 20,
    TAIYIN_STATUS_CATEGORY_TIME = 30,
    TAIYIN_STATUS_CATEGORY_OBSERVER = 40,
    TAIYIN_STATUS_CATEGORY_EVENT = 50,
    TAIYIN_STATUS_CATEGORY_RUNTIME = 60,
    TAIYIN_STATUS_CATEGORY_UNKNOWN = 999,
};

inline bool taiyin_status_ok(TaiyinStatus status) noexcept {
    return status == TAIYIN_STATUS_OK;
}

inline TaiyinStatusCategory taiyin_status_category(TaiyinStatus status) noexcept {
    if (status == TAIYIN_STATUS_OK) {
        return TAIYIN_STATUS_CATEGORY_OK;
    }

    const int32_t code = status < 0 ? -status : status;
    if (code < 1000) return TAIYIN_STATUS_CATEGORY_GENERIC;
    if (code < 2000) return TAIYIN_STATUS_CATEGORY_EPHEMERIS;
    if (code < 3000) return TAIYIN_STATUS_CATEGORY_FILE;
    if (code < 4000) return TAIYIN_STATUS_CATEGORY_TIME;
    if (code < 5000) return TAIYIN_STATUS_CATEGORY_OBSERVER;
    if (code < 6000) return TAIYIN_STATUS_CATEGORY_EVENT;
    if (code < 7000) return TAIYIN_STATUS_CATEGORY_RUNTIME;
    return TAIYIN_STATUS_CATEGORY_UNKNOWN;
}

}  // namespace taiyin

#endif  // TAIYIN_STATUS_H
